### ISSUE TITLE
Bogus internl memory error

### ISSUE THREAD

**Issue by jens-maus** [adtools/abcsh#10]
Very occasionally but for some quirky reason almost everytime I run the perl test suit sh will emit an error stating:

freeing memory outside of block (corrupted?)

and bail out.

changhing line 315 in alloc.c:

from

```
    if (dp < &bp->cell[NOBJECT_FIELDS] || dp >= bp->last)

    to

     if (dp < &bp->cell[NOBJECT_FIELDS] || dp > bp->last)


     fixes this issue.
```

Reported by: Andy Broad andy@broad.ology.org.uk

**Comment by broadblues** [comment]
Fixed at 120dfa9fdea73999fc0a4f4374a01eda3f71da46 (svn commit 142)
