### ISSUE TITLE
CppCheck findings

### ISSUE THREAD

**Issue by capehill** [adtools/abcsh#11]
Checked the project with CppCheck and some issues were found. Results attached.

[findings.txt](https://github.com/adtools/abcsh/files/952649/findings.txt)

http://cppcheck.sourceforge.net/

**Comment by broadblues** [comment]
I checked the only two lines in those "findings" that flagged an error, and they were incorrect t1.tms_utime et al are never used untitialised as the variable tf is set to TF_NOARGS for the case where they are not initialised, and then the value of t1 is only used when ! tf & TF_NOARGS .
