### ISSUE TITLE
"CED crash" crashlog

### ISSUE THREAD

**Issue by jens-maus** [adtools/abcsh#7]
As I can't add information to the original bug, which is:
https://sourceforge.net/tracker/?func=detail&aid=1477829&group\_id=124336&atid=699222

Attached is the crashlog when I run CED from within sh

Reported by: pferrucci

**Comment by ssolie** [comment]
I don't have any crashes with abc-shell 53.5 and CygnusEd 5.60

**Comment by jens-maus** [comment]
Thus, closing this issue.
