### ISSUE TITLE
Incorrect redirection to some non normalised paths

### ISSUE THREAD

**Issue by jens-maus** [adtools/abcsh#9]
The following fails 

echo "# dummy" &gt;././.deps/somefile.Po

with an error 

sh: cannot create ././.deps/somefile.Po: No such file or directory

however 

echo "# dummy" &gt;./.deps/somefile.Po

succedes
clearly abc-shell is having a problem with the non normalised "././" prefix

This often prevents correct creation of deps files in some configure scripts

Reported by: Andy Broad andy@broad.ology.org.uk

**Comment by broadblues** [comment]
This should now be fixed at e75614642b58a8f62ebfa97aed85a89302221c21 (svn commit 141)
